pom.xml
=> publish package to github

.github/workflows/maven-ci.yml
Jira Ticket: [MAT-4164](https://jira.cms.gov/browse/MAT-4164)
=> Snapshot publish gitaction test

pom.xml
Jira Ticket: [MAT-4090](https://jira.cms.gov/browse/MAT-4090)
=> version upgrate test

pom.xml, src/main/java/gov/cms/madiejavamodels/library/CqlLibrary.java
Jira Ticket: [MAT-4164](https://jira.cms.gov/browse/MAT-4164)
=> add elmxml and elm json to cqllibrary(snapshot publish testing)

.github/workflows/maven-ci.yml
Jira Ticket: [MAT-4164](https://jira.cms.gov/browse/MAT-4164)
=> Publish snapshot on push to develop

.github/workflows/release.yml, README.md
Jira Ticket: [MAT-4164](https://jira.cms.gov/browse/MAT-4164)
=> Readme & release action

pom.xml
- Updated the repository distribution id, to avoid id collisions
=> updated distribution repository id

src/main/java/gov/cms/madiejavamodels/measure/MeasurePopulation.java, src/test/java/gov/cms/madiejavamodels/MeasurePopulationTest.java
Jira Ticket: [MAT-4259](https://jira.cms.gov/browse/MAT-4259)
- Conversion from population enum to population code
- Conversion from population enum to population display value 
=> MAT-4259 added population constant conversions(toCode, diaplayValue)

.github/workflows/maven-ci.yml
Jira Ticket: [MAT-4259](https://jira.cms.gov/browse/MAT-4259)
=> updated git secret to use PAT

.github/workflows/maven-ci.yml
Jira Ticket: [MAT-4259](https://jira.cms.gov/browse/MAT-4259)
- Use git actions v3
- Use GITHUB_TOKEN to publish snapshot
=> Update git actions

.github/workflows/maven-ci.yml, pom.xml
Jira Ticket: [MAT-4259](https://jira.cms.gov/browse/MAT-4259)
- we figured out that git package repository id should always be `github`
=> Mat 4259 snapshot publish workflow test

.github/workflows/maven-ci.yml, src/main/java/gov/cms/madiejavamodels/measure/Measure.java
Jira Ticket: [MAT-4319](https://jira.cms.gov/browse/MAT-4319)
=> MAT-4319 update MP date type

src/main/java/gov/cms/madiejavamodels/cql/terminology/CqlCode.java, src/main/java/gov/cms/madiejavamodels/cql/terminology/VsacCode.java, src/main/java/gov/cms/madiejavamodels/mappingData/CodeSystemEntry.java
=> Added Code & code system related models

pom.xml, src/main/java/gov/cms/madiejavamodels/measure/Measure.java
Jira Ticket: [MAT-4213](https://jira.cms.gov/browse/MAT-4213)
=> add transient field for elm xml

src/main/java/gov/cms/madiejavamodels/mappingData/CodeSystemEntry.java
=> updating CodeSystemEntry.version to versions

pom.xml, src/main/java/gov/cms/madie/models/library/CqlLibrary.java, src/main/java/gov/cms/madie/models/library/CqlLibraryDraft.java, src/main/java/gov/cms/madie/models/library/Version.java, src/main/java/gov/cms/madie/models/utils/VersionJsonSerializer.java
Jira Ticket: [MAT-4274](https://jira.cms.gov/browse/MAT-4274)
=> MAT-4274 models for cql library service

src/main/java/gov/cms/madie/models/common/ActionType.java
Jira Ticket: [MAT-4469](https://jira.cms.gov/browse/MAT-4469)
=> MAT-4699 add imported type for measure service

src/main/java/gov/cms/madie/models/measure/Group.java, src/main/java/gov/cms/madie/models/measure/MeasureGroupTypes.java
Jira Ticket: [MAT-4474](https://jira.cms.gov/browse/MAT-4474)
=> Adding MeasureGroupTypes

src/main/java/gov/cms/madie/models/measure/Group.java
No JIRA! Trying to fix issue with group creation in Dev
=> remove NotEmpty validation on Group - measureGroupTypes to fix issue with group creation

pom.xml, src/main/java/gov/cms/madie/models/measure/Group.java, src/main/java/gov/cms/madie/models/measure/GroupScoringPopulation.java, src/main/java/gov/cms/madie/models/measure/MeasurePopulationOption.java, src/main/java/gov/cms/madie/models/measure/Population.java, src/main/java/gov/cms/madie/models/measure/PopulationType.java, src/main/java/gov/cms/madie/models/utils/ScoringPopulationDefinition.java, src/main/java/gov/cms/madie/models/validators/GroupScoringPopulationValidator.java, src/main/java/gov/cms/madie/models/validators/ScoringPopulationValidator.java, src/test/java/gov/cms/madie/models/MeasurePopulationTest.java, src/test/java/gov/cms/madie/models/validators/GroupScoringPopulationValidatorTest.java, src/test/java/gov/cms/madie/models/validators/ScoringPopulationValidatorTest.java
[MAT-4427](https://jira.cms.gov/browse/MAT-4427) Add Second Initial Population for Ratio Measures
Jira Ticket: [MAT-4427](https://jira.cms.gov/browse/MAT-4427)
- Updated group model to support the same population multiple times. Now we can have 2 IPs
- Updated validator
*  If you have any concerns they are brought up either to the developer …
=> MAT-4427 update models for adding second IP

src/main/java/gov/cms/madie/models/common/ActionType.java
Jira Ticket: [MAT-4469](https://jira.cms.gov/browse/MAT-4469)
=> MAT-4469 add action type update

src/main/java/gov/cms/madie/models/measure/Group.java
=> Add required field validations for measure group types

.github/workflows/maven-ci.yml, pom.xml, src/main/java/gov/cms/madie/models/measure/Group.java, src/main/java/gov/cms/madie/models/measure/Stratification.java
Jira Ticket: [MAT-4489](https://jira.cms.gov/browse/MAT-4489)
=> Mat 4489 - Add Stratifications 

src/main/java/gov/cms/madie/models/measure/Group.java
Jira Ticket: [MAT-4501](https://jira.cms.gov/browse/MAT-4501)
=> MAT-4501 adding group scoring unit

.github/workflows/maven-ci.yml, pom.xml
Jira Ticket: [MAT-4501](https://jira.cms.gov/browse/MAT-4501)
=> bump version

src/main/java/gov/cms/madie/models/measure/Group.java
Jira Ticket: [MAT-4501](https://jira.cms.gov/browse/MAT-4501)
=> temporarily comment out stratifications for github build issues

src/main/java/gov/cms/madie/models/measure/Group.java
Jira Ticket: [MAT-4489](https://jira.cms.gov/browse/MAT-4489)
=> Reenable stratifciations

src/main/java/gov/cms/madie/models/measure/AssociationType.java, src/main/java/gov/cms/madie/models/measure/Population.java
Jira Ticket: [MAT-4495](https://jira.cms.gov/browse/MAT-4495)
=> MAT-4495 initial population association

pom.xml, src/main/java/gov/cms/madie/models/measure/Group.java
added validations for population basis
=> Bug 4630/population basis validation

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java
Jira Ticket: [MAT-4570](https://jira.cms.gov/browse/MAT-4570)
=> MAT-4570 eCQM Title

src/main/java/gov/cms/madie/models/measure/Measure.java
Jira Ticket: [MAT-4570](https://jira.cms.gov/browse/MAT-4570)
=> update validation sequence for tests

pom.xml, src/main/java/gov/cms/madie/models/measure/HapiOperationOutcome.java
=> add boolean flag for HAPI validator output

pom.xml, src/main/java/gov/cms/madie/models/common/ModelType.java
Jira Ticket: [MAT-4574](https://jira.cms.gov/browse/MAT-4574)
=> change model type to QI-Core v4.1.1

pom.xml, src/main/java/gov/cms/madie/models/library/CqlLibraryDraft.java
Jira Ticket: [MAT-4618](https://jira.cms.gov/browse/MAT-4618)
added extra field for Cql library draft modal to accomodate and save updated Cql 
=> added extra field for Cql library draft

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java
Jira Ticket: [MAT-4598](https://jira.cms.gov/browse/MAT-4598)
=> MAT-4598 version ID

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java
Jira Ticket: [MAT-4674](https://jira.cms.gov/browse/MAT-4674)
=> MAT-4674 CMS ID

pom.xml, src/main/java/gov/cms/madie/models/measure/TestCaseGroupPopulation.java, src/main/java/gov/cms/madie/models/measure/TestCasePopulationValue.java
Jira Ticket: [MAT-4666](https://jira.cms.gov/browse/MAT-4666)
=> add populationBasis and change test case values to Object

pom.xml, src/main/java/gov/cms/madie/models/measure/MeasureMetaData.java
Jira Ticket: [MAT-3616](https://jira.cms.gov/browse/MAT-3616)
This PR adds a single property to the measure metaData
=> MAT-3616: Add a clinicalReocmmendation field for measure-metaData

pom.xml, src/main/java/gov/cms/madie/models/measure/Endorsement.java, src/main/java/gov/cms/madie/models/measure/MeasureMetaData.java, src/main/java/gov/cms/madie/models/measure/Population.java, src/main/java/gov/cms/madie/models/measure/Reference.java
Jira Ticket: [MAT-4736](https://jira.cms.gov/browse/MAT-4736)
=> Mat 4736 import measure metadata

pom.xml, src/main/java/gov/cms/madie/models/measure/TestCaseGroupPopulation.java, src/main/java/gov/cms/madie/models/measure/TestCaseStratificationValue.java
Jira Ticket: [MAT-4732](https://jira.cms.gov/browse/MAT-4732)
Saving the stratifications 
=> save stratification values

pom.xml, src/main/java/gov/cms/madie/models/measure/TestCasePopulationValue.java, src/main/java/gov/cms/madie/models/validators/ScoringPopulationValidator.java
Jira Ticket: [MAT-4702](https://jira.cms.gov/browse/MAT-4702)
Saving measure observations
=> save observation values

pom.xml, src/main/java/gov/cms/madie/models/measure/TestCase.java
Jira Ticket: [MAT-4425](https://jira.cms.gov/browse/MAT-4425)
using the valid resource property
=> using the valid resource property

pom.xml, src/main/java/gov/cms/madie/models/measure/AggregateMethodType.java, src/main/java/gov/cms/madie/models/measure/TestCase.java, src/main/java/gov/cms/madie/models/validators/MeasureObservationValidator.java
Jira Ticket: [MAT-4692](https://jira.cms.gov/browse/MAT-4692)
Updating aggregate function drop down
=> Updating aggregate function drop down

pom.xml, src/main/java/gov/cms/madie/models/measure/PopulationType.java, src/main/java/gov/cms/madie/models/utils/ScoringPopulationDefinition.java, src/main/java/gov/cms/madie/models/validators/GroupScoringPopulationValidator.java, src/main/java/gov/cms/madie/models/validators/ScoringPopulationValidator.java, src/test/java/gov/cms/madie/models/validators/GroupScoringPopulationValidatorTest.java, src/test/java/gov/cms/madie/models/validators/ScoringPopulationValidatorTest.java
Jira Ticket: [MAT-4943](https://jira.cms.gov/browse/MAT-4943)
Added PopulationTypes that are used to distinguish between the measureObservations added to the measure populatinos and the generated observations added to test cases 
=> MAT-4943: Adding types for Obse3rvations and updating validators

pom.xml
=> Release: Removing snapshot

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java, src/test/java/gov/cms/madie/models/validators/ScoringPopulationValidatorTest.java
Jira Ticket: [MAT-5191](https://jira.cms.gov/browse/MAT-5191)
=> MAT-5191 refactor measure version from string to object

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java
Jira Ticket: [MAT-5191](https://jira.cms.gov/browse/MAT-5191)
=> Mat 5191 measure version refactor

pom.xml, src/main/java/gov/cms/madie/models/scanner/ScanValidationDto.java, src/main/java/gov/cms/madie/models/scanner/VirusScanResponseDto.java, src/main/java/gov/cms/madie/models/scanner/VirusScanResultDto.java
Jira Ticket: [MAT-5239](https://jira.cms.gov/browse/MAT-5239)
=> add virus scanner models

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java, src/main/java/gov/cms/madie/models/measure/RiskAdjustment.java, src/main/java/gov/cms/madie/models/measure/SupplementalData.java
Jira Ticket: [MAT-5253](https://jira.cms.gov/browse/MAT-5253)
=> MAT-5253: Add supplemental data and risk adjustment

.github/workflows/maven-ci.yml, pom.xml
Jira Ticket: [MAT-5291](https://jira.cms.gov/browse/MAT-5291)
Update spring-boot-starter-data and add a dependency for spring-boot-starter
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-mongodb/3.0.2
Goal: "Update Spring-Framework for anything that pulls in org.springframework:spring-beans to be upgraded to @5.2.20 or @5.3.18"
This PR updates passed 5.3.18
*  The tests …
=> MAT-5291: Update spring-boot-starter-data for 

pom.xml, src/main/java/gov/cms/madie/models/measure/MeasureObservation.java
Jira Ticket: [MAT-5359](https://jira.cms.gov/browse/MAT-5359)
=> MAT-5359: Add a description field to MeasureObservation

package-lock.json, pom.xml, src/main/java/gov/cms/madie/models/common/ProgramUseContext.java, src/main/java/gov/cms/madie/models/library/CqlLibrary.java
Jira Ticket: [MAT-5431](https://jira.cms.gov/browse/MAT-543`)
https://github.com/MeasureAuthoringTool/cql-library-service/pull/38
=> MAT-5431: Add in new fields (library.useContext)

pom.xml, src/main/java/gov/cms/madie/models/common/Organization.java
Jira Ticket: [MAT-5407](https://jira.cms.gov/browse/MAT-5407)
added url field to organizations
=> added url field to organizations

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java, src/main/java/gov/cms/madie/models/measure/ReviewMetaData.java
Jira Ticket: [MAT-5387](https://jira.cms.gov/browse/MAT-5387)
=> MAT-5387 add approval date and last review date

pom.xml, src/main/java/gov/cms/madie/models/common/EndorserOrganization.java, src/main/java/gov/cms/madie/models/measure/Endorsement.java
Jira Ticket: [MAT-5393](https://jira.cms.gov/browse/MAT-5393)
=> MAT-5393: change endorsement fields

pom.xml, src/main/java/gov/cms/madie/models/measure/ReviewMetaData.java
Jira Ticket: [MAT-5387](https://jira.cms.gov/browse/MAT-5387)
=> change date to localdate

pom.xml, src/main/java/gov/cms/madie/models/measure/ReviewMetaData.java
Jira Ticket: [MAT-5387](https://jira.cms.gov/browse/MAT-5387)
=> change to Instant

src/main/java/gov/cms/madie/models/measure/Measure.java
Jira Ticket: [MAT-5369](https://jira.cms.gov/browse/MAT-5369)
MAT-5369 is related to verifying CQL definitions for SupplementalData.  This just adds a @singular to allow a builder method that makes it easier to create the list for testing
*  If you have any concerns they are brought up either to the developer assigned, security engineer, or …
=> MAT-5369_AddingABuilderAnnotationForSupplementalData

pom.xml, src/main/java/gov/cms/madie/models/measure/Endorsement.java, src/main/java/gov/cms/madie/models/measure/Measure.java, src/main/java/gov/cms/madie/models/measure/MeasureMetaData.java, src/main/java/gov/cms/madie/models/validators/RequiredByOtherFieldValidator.java, src/main/java/gov/cms/madie/models/validators/RequiredOnSelect.java, src/test/java/gov/cms/madie/models/validators/RequiredByOtherFieldValidatorTest.java
Jira Ticket: [MAT-5393](https://jira.cms.gov/browse/MAT-5393)
=> MAT-5393: add validation for endorsement

pom.xml
=> Release_Zelda: Removing Snapshot

pom.xml, src/main/java/gov/cms/madie/models/measure/DefDescPair.java, src/main/java/gov/cms/madie/models/measure/Measure.java, src/main/java/gov/cms/madie/models/measure/RiskAdjustment.java, src/main/java/gov/cms/madie/models/measure/SupplementalData.java
Jira Ticket: [MAT-5464](https://jira.cms.gov/browse/MAT-5464)
Some refactoring to make the upstream code a little less redundant
=> MAT-5464: Adding for RAV Data

pom.xml, src/main/java/gov/cms/madie/models/measure/Endorsement.java, src/main/java/gov/cms/madie/models/validators/RequiredByOtherFieldValidator.java, src/test/java/gov/cms/madie/models/validators/RequiredByOtherFieldValidatorTest.java
Jira Ticket: [MAT-5507](https://jira.cms.gov/browse/MAT-5507)
=> MAT-5507 add validation for endorser being null

pom.xml, src/main/java/gov/cms/madie/models/common/ModelType.java
Jira Ticket: [MAT-5449](https://jira.cms.gov/browse/MAT-5449)
=> add QDM version for model type and bump patch version

pom.xml, src/main/java/gov/cms/madie/models/measure/Export.java, src/main/java/gov/cms/madie/models/measure/Measure.java
Jira Ticket: [MAT-5513](https://jira.cms.gov/browse/MAT-5513)
Adding measure bundle JSON to Measure so that we can save JSON and lock it down when a measure is versioned. 
=> Added measure bundle json to Measure

pom.xml, src/main/java/gov/cms/madie/models/library/CqlLibrary.java, src/main/java/gov/cms/madie/models/library/CqlLibraryDraft.java, src/main/java/gov/cms/madie/models/measure/Endorsement.java, src/main/java/gov/cms/madie/models/measure/Group.java, src/main/java/gov/cms/madie/models/measure/Measure.java, src/main/java/gov/cms/madie/models/measure/MeasureMetaData.java, src/main/java/gov/cms/madie/models/measure/MeasureObservation.java, src/main/java/gov/cms/madie/models/measure/Population.java, src/main/java/gov/cms/madie/models/measure/Stratification.java, src/main/java/gov/cms/madie/models/measure/TestCase.java, src/main/java/gov/cms/madie/models/validators/EnumValidator.java, src/main/java/gov/cms/madie/models/validators/EnumValidatorImpl.java, src/main/java/gov/cms/madie/models/validators/GroupScoringPopulationValidator.java, src/main/java/gov/cms/madie/models/validators/MeasureObservationValidator.java, src/main/java/gov/cms/madie/models/validators/RequiredByOtherFieldValidator.java, src/main/java/gov/cms/madie/models/validators/RequiredOnSelect.java, src/main/java/gov/cms/madie/models/validators/ScoringPopulationValidator.java, src/main/java/gov/cms/madie/models/validators/ValidGroupScoringPopulation.java, src/main/java/gov/cms/madie/models/validators/ValidMeasureObservation.java, src/main/java/gov/cms/madie/models/validators/ValidScoringPopulation.java, src/test/java/gov/cms/madie/models/validators/GroupScoringPopulationValidatorTest.java, src/test/java/gov/cms/madie/models/validators/MeasureObservationValidatorTest.java, src/test/java/gov/cms/madie/models/validators/RequiredByOtherFieldValidatorTest.java, src/test/java/gov/cms/madie/models/validators/ScoringPopulationValidatorTest.java
Jira Ticket: [MAT-5523](https://jira.cms.gov/browse/MAT-5523)
https://github.com/MeasureAuthoringTool/cql-library-service/pull/41
=> Jakarta change and version number bump

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java, src/main/java/gov/cms/madie/models/measure/QdmMeasure.java, src/main/java/gov/cms/madie/models/validators/MeasureScoringValidator.java, src/main/java/gov/cms/madie/models/validators/ValidMeasureScoring.java, src/test/java/gov/cms/madie/models/validators/MeasureScoringValidatorTest.java
Jira Ticket: [MAT-5533](https://jira.cms.gov/browse/MAT-5533)
=> remove qdm scoring required validation

pom.xml, src/main/java/gov/cms/madie/models/library/CqlLibrary.java, src/main/java/gov/cms/madie/models/library/CqlLibraryDraft.java, src/main/java/gov/cms/madie/models/measure/Endorsement.java, src/main/java/gov/cms/madie/models/measure/Group.java, src/main/java/gov/cms/madie/models/measure/Measure.java, src/main/java/gov/cms/madie/models/measure/MeasureMetaData.java, src/main/java/gov/cms/madie/models/measure/MeasureObservation.java, src/main/java/gov/cms/madie/models/measure/Population.java, src/main/java/gov/cms/madie/models/measure/Stratification.java, src/main/java/gov/cms/madie/models/measure/TestCase.java, src/main/java/gov/cms/madie/models/validators/EnumValidator.java, src/main/java/gov/cms/madie/models/validators/EnumValidatorImpl.java, src/main/java/gov/cms/madie/models/validators/GroupScoringPopulationValidator.java, src/main/java/gov/cms/madie/models/validators/MeasureObservationValidator.java, src/main/java/gov/cms/madie/models/validators/MeasureScoringValidator.java, src/main/java/gov/cms/madie/models/validators/RequiredByOtherFieldValidator.java, src/main/java/gov/cms/madie/models/validators/RequiredOnSelect.java, src/main/java/gov/cms/madie/models/validators/ScoringPopulationValidator.java, src/main/java/gov/cms/madie/models/validators/ValidGroupScoringPopulation.java, src/main/java/gov/cms/madie/models/validators/ValidMeasureObservation.java, src/main/java/gov/cms/madie/models/validators/ValidMeasureScoring.java, src/main/java/gov/cms/madie/models/validators/ValidScoringPopulation.java, src/test/java/gov/cms/madie/models/validators/GroupScoringPopulationValidatorTest.java, src/test/java/gov/cms/madie/models/validators/MeasureObservationValidatorTest.java, src/test/java/gov/cms/madie/models/validators/MeasureScoringValidatorTest.java, src/test/java/gov/cms/madie/models/validators/RequiredByOtherFieldValidatorTest.java, src/test/java/gov/cms/madie/models/validators/ScoringPopulationValidatorTest.java
Jira Ticket: [MAT-5523](https://jira.cms.gov/browse/MAT-5523)
=> Mat 5523 upgrade to jakarta

pom.xml
Jira Ticket: [MAT-5528](https://jira.cms.gov/browse/MAT-5528)
=> MAT-5538 update springboot dependencies to 3.x

pom.xml, src/main/java/gov/cms/madie/models/measure/FhirMeasure.java, src/main/java/gov/cms/madie/models/measure/Group.java, src/main/java/gov/cms/madie/models/measure/QdmMeasure.java, src/main/java/gov/cms/madie/models/validators/QDMGroupScoringValidator.java, src/main/java/gov/cms/madie/models/validators/ValidFhirGroup.java, src/main/java/gov/cms/madie/models/validators/ValidFhirGroupValidator.java, src/main/java/gov/cms/madie/models/validators/ValidQDMGroupScoring.java, src/test/java/gov/cms/madie/models/validators/FhirGroupValidatorTest.java, src/test/java/gov/cms/madie/models/validators/QDMGroupScoringValidatorTest.java
Jira Ticket: [MAT-5535](https://jira.cms.gov/browse/MAT-5535)
=> Mat 5535 qdm scoring unit

pom.xml, src/main/java/gov/cms/madie/models/measure/QdmMeasure.java
Jira Ticket: [MAT-5552](https://jira.cms.gov/browse/MAT-5552)
=> MAT-5552: add rate aggregation

pom.xml, src/main/java/gov/cms/madie/models/measure/MeasureSet.java, src/main/java/gov/cms/madie/models/measure/ResourceAcl.java
Jira Ticket: [MAT-5587](https://jira.cms.gov/browse/MAT-5587)
=> MAT-5587 moving acls to measureset

pom.xml, src/main/java/gov/cms/madie/models/measure/QdmMeasure.java
Jira Ticket: [MAT-5553](https://jira.cms.gov/browse/MAT-5553)
=> Adding improvement notation to measure for QDM

pom.xml, src/main/java/gov/cms/madie/models/common/ImprovementNotation.java, src/main/java/gov/cms/madie/models/measure/QdmMeasure.java
Jira Ticket: [MAT-5553](https://jira.cms.gov/browse/MAT-5553)
=> Adding validations for Improvement notation

pom.xml, src/main/java/gov/cms/madie/models/measure/FhirMeasure.java, src/main/java/gov/cms/madie/models/measure/Measure.java, src/main/java/gov/cms/madie/models/measure/QdmMeasure.java, src/main/java/gov/cms/madie/models/measure/qdm/QdmTestCase.java, src/main/java/gov/cms/madie/models/measure/qdm/QdmTestCaseGroupPopulation.java, src/main/java/gov/cms/madie/models/validators/qdm/QdmScoringPopulationValidator.java, src/main/java/gov/cms/madie/models/validators/qdm/QdmValidScoringPopulation.java
Jira Ticket: [MAT-5644](https://jira.cms.gov/browse/MAT-5644)
=> branching QDM Testcases for qdm specific valdiations

pom.xml
Jira Ticket: None; release activity
=> Bumping to SNAPSHOT to release

.github/workflows/release.yml
=> Fixing release.ml for java version

.github/workflows/release.yml
=> Release 5.1

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java
Jira Ticket: [MAT-5762](https://jira.cms.gov/browse/MAT-5762)
Adding risk Adjustment description to measure level for QDM 
=> Added riskAdjustmnet description to measure level

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java
Jira Ticket: [MAT-5761](https://jira.cms.gov/browse/MAT-5761)
=> MAT-5761: add supplemental data description

pom.xml, src/main/java/gov/cms/madie/models/library/CqlLibrary.java, src/main/java/gov/cms/madie/models/library/LibrarySet.java
- Updatethe madie-java-models for adding new librarySet Collection ( to accommodate the owner role, with fields  acls and owner)
Jira Ticket: [MAT-5808](https://jira.cms.gov/browse/MAT-5808)
=> MAT-5805: Add librarySet to cqlLibrary model

pom.xml, src/main/java/gov/cms/madie/models/library/CqlLibrary.java
Please enter the commit message for your changes. Lines starting
Jira Ticket: [MAT-5808](https://jira.cms.gov/browse/MAT-5808)
=> MAT-58085: deprecate groupID

pom.xml, src/main/java/gov/cms/madie/models/library/LibrarySet.java
Jira Ticket: [MAT-5808](https://jira.cms.gov/browse/MAT-5808)
=> Make librarySetID indexed and unique

pom.xml, src/main/java/gov/cms/madie/models/measure/TestCase.java
Jira Ticket: [MAT-5922](https://jira.cms.gov/browse/MAT-5922)
=> MAT-5922 add patientId for testcase

pom.xml, src/main/java/gov/cms/madie/models/measure/TestCaseImportOutcome.java, src/main/java/gov/cms/madie/models/measure/TestCaseImportRequest.java
Jira Ticket: [MAT-5926](https://jira.cms.gov/browse/MAT-5926)
Using new Data objects for test case imports and provide outcomes with specific failure messages.
=> Added TestCase import request and outcome models

pom.xml, src/main/java/gov/cms/madie/models/measure/Stratification.java
Jira Ticket: [MAT-5977](https://jira.cms.gov/browse/MAT-5977)
removing notnull annotation for associations
=> removed notnull annotation for associations

pom.xml, src/main/java/gov/cms/madie/models/measure/Measure.java
Jira Ticket: [MAT-5984](https://jira.cms.gov/browse/MAT-5984)
=> MAT-5984 remove ProgramUseContext from Measure

pom.xml, src/main/java/gov/cms/madie/models/library/CqlLibrary.java, src/main/java/gov/cms/madie/models/library/CqlLibraryDraft.java
Jira Ticket: [MAT-6106](https://jira.cms.gov/browse/MAT-6106)
https://github.com/MeasureAuthoringTool/cql-library-service/pull/52
https://github.com/MeasureAuthoringTool/madie-cql-library/pull/96
=> MAT-6106: Change library name character limit

pom.xml
Remove SNAPSHOT declaration for release.
=> Bump to release

pom.xml
Jira Ticket: [MAT-6058](https://jira.cms.gov/browse/MAT-6058)
=> MAT-6058: Bumping to snapshot to continue work associated with 6058

src/main/java/gov/cms/madie/models/common/ModelType.java
Jira Ticket: [MAT-6058](https://jira.cms.gov/browse/MAT-6058)
Added a value to the modelType enum that can be used to dynamically construct class names to enable runtime service lookup
=> MAT-6058: Adding ShortValue to help with Model class lookups

src/main/java/gov/cms/madie/models/common/BundleType.java, src/main/java/gov/cms/madie/models/dto/ExportDTO.java
Jira Ticket: [MAT-6024](https://jira.cms.gov/browse/MAT-6024)
Couple object changes to facilitate the export of Bundles with "Transaction" type
=> MAT-6204:  Adding types to facilitate Export by BundleType

pom.xml
Jira Ticket: [MAT-6204](https://jira.cms.gov/browse/MAT-6204)
=> Bumping to 0.6.8 RELEASE

pom.xml, src/main/java/gov/cms/madie/models/common/BundleType.java, src/main/java/gov/cms/madie/models/common/ModelType.java, src/main/java/gov/cms/madie/models/dto/ExportDTO.java
=> 0.6.8 Final
